base.url=https://opensource-demo.orangehrmlive.com

connect.timeout=3000
read.timeout=5000

retry.count=3
retry.interval=2000

poll.timeout=10000
poll.interval=1000

proxy.enabled=false
proxy.host=localhost
proxy.port=8080